[2019-12-21 14:26:40,854]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 405, "method": "POST", "code": "405 METHOD NOT ALLOWED", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "The method is not allowed for the requested URL."}}
[2019-12-21 14:27:31,231]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 20, in post
    data = requests.post( self.parallel_host, data={"api_key": parallel_apikey ,"url":args['url']}).text
NameError: name 'parallel_apikey' is not defined
[2019-12-21 14:27:31,236]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 14:28:31,011]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 20, in post
    data = requests.post( self.parallel_host, data={"api_key": parallel_apikey ,"url":args['url']}).text
NameError: name 'parallel_apikey' is not defined
[2019-12-21 14:28:31,014]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 14:31:32,649]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 20, in post
    data = requests.post( self.parallel_host, params={"api_key": parallel_apikey ,"url":args['url']}).text
NameError: name 'parallel_apikey' is not defined
[2019-12-21 14:31:32,652]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?url=http://www.tentik.com/wp-content/uploads/2017/07/tradisimakanindo7.jpg", "request": {"url": "http://www.tentik.com/wp-content/uploads/2017/07/tradisimakanindo7.jpg"}, "response": {"message": "Internal Server Error"}}
[2019-12-21 14:33:01,608]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 22, in post
    tag = jsdata['tag']
TypeError: 'method' object is not subscriptable
[2019-12-21 14:33:01,610]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?url=http://www.tentik.com/wp-content/uploads/2017/07/tradisimakanindo7.jpg", "request": {"url": "http://www.tentik.com/wp-content/uploads/2017/07/tradisimakanindo7.jpg"}, "response": {"message": "Internal Server Error"}}
[2019-12-21 14:37:58,877]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 21, in post
    jsdata = data.json
AttributeError: 'str' object has no attribute 'json'
[2019-12-21 14:37:58,879]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 14:44:52,582]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 21, in post
    jsdata = data.json
AttributeError: 'str' object has no attribute 'json'
[2019-12-21 14:44:52,583]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 14:46:24,433]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 21, in post
    jsdata = data.json
AttributeError: 'str' object has no attribute 'json'
[2019-12-21 14:46:24,434]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 14:48:17,484]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 22, in post
    tag = jsdata['tag']
TypeError: 'method' object is not subscriptable
[2019-12-21 14:48:17,487]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 14:49:48,112]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 22, in post
    tag = jsdata['tag']
TypeError: 'method' object is not subscriptable
[2019-12-21 14:49:48,114]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?url=https://cdn2.tstatic.net/travel/foto/bank/images/ilustrasi-orang-makan.jpg", "request": {"url": "https://cdn2.tstatic.net/travel/foto/bank/images/ilustrasi-orang-makan.jpg"}, "response": {"message": "Internal Server Error"}}
[2019-12-21 14:50:18,115]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 22, in post
    tag = jsdata['tag']
KeyError: 'tag'
[2019-12-21 14:50:18,118]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?url=https://cdn2.tstatic.net/travel/foto/bank/images/ilustrasi-orang-makan.jpg", "request": {"url": "https://cdn2.tstatic.net/travel/foto/bank/images/ilustrasi-orang-makan.jpg"}, "response": {"message": "Internal Server Error"}}
[2019-12-21 14:52:57,429]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 22, in post
    tag = jsdata['tag']
KeyError: 'tag'
[2019-12-21 14:52:57,433]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?url=https://cdn2.tstatic.net/travel/foto/bank/images/ilustrasi-orang-makan.jpg", "request": {"url": "https://cdn2.tstatic.net/travel/foto/bank/images/ilustrasi-orang-makan.jpg"}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:02:02,740]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 21, in post
    jsdata = data.json()
AttributeError: 'str' object has no attribute 'json'
[2019-12-21 15:02:02,744]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:02:53,415]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 21, in post
    jsdata = data.json()
AttributeError: 'str' object has no attribute 'json'
[2019-12-21 15:02:53,416]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:03:03,844]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 21, in post
    jsdata = data.json()
AttributeError: 'str' object has no attribute 'json'
[2019-12-21 15:03:03,846]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:05:13,407]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 22, in post
    tag = data['tag']
TypeError: string indices must be integers
[2019-12-21 15:05:13,411]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:05:18,422]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 22, in post
    tag = data['tag']
TypeError: string indices must be integers
[2019-12-21 15:05:18,423]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:06:54,271]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"code\":400,\"message\":\"No image file\"}"}
[2019-12-21 15:08:04,312]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"code\":400,\"message\":\"No image file\"}"}
[2019-12-21 15:09:19,779]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:09:26,745]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:09:49,783]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:11:49,079]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:11:57,680]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:12:07,978]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    data = requests.post( "https://apis.paralleldots.com/v4/object_recognizer", data={ "api_key": self.parallel_apikey } ,files={"file": open("<path_to_image>","rb")}).text
FileNotFoundError: [Errno 2] No such file or directory: '<path_to_image>'
[2019-12-21 15:12:07,981]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:12:10,846]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    data = requests.post( "https://apis.paralleldots.com/v4/object_recognizer", data={ "api_key": self.parallel_apikey } ,files={"file": open("<path_to_image>","rb")}).text
FileNotFoundError: [Errno 2] No such file or directory: '<path_to_image>'
[2019-12-21 15:12:10,847]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:12:12,471]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    data = requests.post( "https://apis.paralleldots.com/v4/object_recognizer", data={ "api_key": self.parallel_apikey } ,files={"file": open("<path_to_image>","rb")}).text
FileNotFoundError: [Errno 2] No such file or directory: '<path_to_image>'
[2019-12-21 15:12:12,472]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:12:13,332]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    data = requests.post( "https://apis.paralleldots.com/v4/object_recognizer", data={ "api_key": self.parallel_apikey } ,files={"file": open("<path_to_image>","rb")}).text
FileNotFoundError: [Errno 2] No such file or directory: '<path_to_image>'
[2019-12-21 15:12:13,334]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:12:14,094]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    data = requests.post( "https://apis.paralleldots.com/v4/object_recognizer", data={ "api_key": self.parallel_apikey } ,files={"file": open("<path_to_image>","rb")}).text
FileNotFoundError: [Errno 2] No such file or directory: '<path_to_image>'
[2019-12-21 15:12:14,095]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:13:02,640]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    # data = requests.post( "https://apis.paralleldots.com/v4/object_recognizer", data={ "api_key": self.parallel_apikey } ,files={"file": open("<path_to_image>","rb")}).text
FileNotFoundError: [Errno 2] No such file or directory: '<path_to_image>'
[2019-12-21 15:13:02,641]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:13:04,415]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    # data = requests.post( "https://apis.paralleldots.com/v4/object_recognizer", data={ "api_key": self.parallel_apikey } ,files={"file": open("<path_to_image>","rb")}).text
FileNotFoundError: [Errno 2] No such file or directory: '<path_to_image>'
[2019-12-21 15:13:04,417]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:13:07,039]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    # data = requests.post( "https://apis.paralleldots.com/v4/object_recognizer", data={ "api_key": self.parallel_apikey } ,files={"file": open("<path_to_image>","rb")}).text
FileNotFoundError: [Errno 2] No such file or directory: '<path_to_image>'
[2019-12-21 15:13:07,040]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:13:18,167]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:13:20,719]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:14:14,385]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:15:36,305]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:17:38,299]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:17:43,896]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:19:08,070]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"code\":400,\"message\":\"No image file\"}"}
[2019-12-21 15:19:11,449]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"code\":400,\"message\":\"No image file\"}"}
[2019-12-21 15:21:08,703]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?url=https://i.ytimg.com/vi/21u1UAwX7JA/maxresdefault.jpg", "request": {"url": "https://i.ytimg.com/vi/21u1UAwX7JA/maxresdefault.jpg"}, "response": "{\"code\":400,\"message\":\"No image file\"}"}
[2019-12-21 15:21:42,592]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?url=https://i.ytimg.com/vi/21u1UAwX7JA/maxresdefault.jpg", "request": {"url": "https://i.ytimg.com/vi/21u1UAwX7JA/maxresdefault.jpg"}, "response": "{\"code\":400,\"message\":\"No image file\"}"}
[2019-12-21 15:21:49,241]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"code\":400,\"message\":\"No image file\"}"}
[2019-12-21 15:27:33,153]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/object_recognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:27:37,005]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/object_recognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:28:48,069]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"Error\":\"Error reading Image from URL. Please try some other URL.\",\"code\":400}"}
[2019-12-21 15:29:22,686]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"output\":[{\"tag\":\"Art\",\"score\":0.40754357},{\"tag\":\"Food\",\"score\":0.27293992},{\"tag\":\"Play\",\"score\":0.241263077},{\"tag\":\"Meal\",\"score\":0.207908183},{\"tag\":\"Yellow\",\"score\":0.177275434},{\"tag\":\"Design\",\"score\":0.133492187},{\"tag\":\"Toy\",\"score\":0.089353576},{\"tag\":\"Lunch\",\"score\":0.068848282},{\"tag\":\"Person\",\"score\":0.068477534},{\"tag\":\"Clothing\",\"score\":0.064856313}]}"}
[2019-12-21 15:43:16,235]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 22, in post
    output = data.json()
AttributeError: 'str' object has no attribute 'json'
[2019-12-21 15:43:16,238]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:44:09,080]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 25, in post
    {'tag': data['output']['tag'=='food'],
TypeError: string indices must be integers
[2019-12-21 15:44:09,083]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:44:23,510]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 25, in post
    {'tag': data['output']['tag'],
TypeError: string indices must be integers
[2019-12-21 15:44:23,513]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:44:53,720]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 25, in post
    {'tag': data['output'][0]['tag'],
TypeError: string indices must be integers
[2019-12-21 15:44:53,724]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:45:08,467]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"output\":[{\"tag\":\"Art\",\"score\":0.40754357},{\"tag\":\"Food\",\"score\":0.27293992},{\"tag\":\"Play\",\"score\":0.241263077},{\"tag\":\"Meal\",\"score\":0.207908183},{\"tag\":\"Yellow\",\"score\":0.177275434},{\"tag\":\"Design\",\"score\":0.133492187},{\"tag\":\"Toy\",\"score\":0.089353576},{\"tag\":\"Lunch\",\"score\":0.068848282},{\"tag\":\"Person\",\"score\":0.068477534},{\"tag\":\"Clothing\",\"score\":0.064856313}]}"}
[2019-12-21 15:48:24,772]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 24, in post
    'tag': data['output'][0]['tag'],
TypeError: string indices must be integers
[2019-12-21 15:48:24,775]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:49:59,289]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 24, in post
    #         'tag': data['output'][0]['tag'],
TypeError: string indices must be integers
[2019-12-21 15:49:59,290]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:50:10,303]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"output\":[{\"tag\":\"Art\",\"score\":0.40754357},{\"tag\":\"Food\",\"score\":0.27293992},{\"tag\":\"Play\",\"score\":0.241263077},{\"tag\":\"Meal\",\"score\":0.207908183},{\"tag\":\"Yellow\",\"score\":0.177275434},{\"tag\":\"Design\",\"score\":0.133492187},{\"tag\":\"Toy\",\"score\":0.089353576},{\"tag\":\"Lunch\",\"score\":0.068848282},{\"tag\":\"Person\",\"score\":0.068477534},{\"tag\":\"Clothing\",\"score\":0.064856313}]}"}
[2019-12-21 15:51:34,665]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 24, in post
    'tag': data['data'][0]['tag'],
TypeError: string indices must be integers
[2019-12-21 15:51:34,667]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:52:01,966]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 24, in post
    'tag': data[0]['tag'],
TypeError: string indices must be integers
[2019-12-21 15:52:01,968]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:52:35,147]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"output\":[{\"tag\":\"Art\",\"score\":0.40754357},{\"tag\":\"Food\",\"score\":0.27293992},{\"tag\":\"Play\",\"score\":0.241263077},{\"tag\":\"Meal\",\"score\":0.207908183},{\"tag\":\"Yellow\",\"score\":0.177275434},{\"tag\":\"Design\",\"score\":0.133492187},{\"tag\":\"Toy\",\"score\":0.089353576},{\"tag\":\"Lunch\",\"score\":0.068848282},{\"tag\":\"Person\",\"score\":0.068477534},{\"tag\":\"Clothing\",\"score\":0.064856313}]}"}
[2019-12-21 15:57:37,132]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    return data['output'][0]
TypeError: string indices must be integers
[2019-12-21 15:57:37,134]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:57:58,592]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"output\":[{\"tag\":\"Art\",\"score\":0.40754357},{\"tag\":\"Food\",\"score\":0.27293992},{\"tag\":\"Play\",\"score\":0.241263077},{\"tag\":\"Meal\",\"score\":0.207908183},{\"tag\":\"Yellow\",\"score\":0.177275434},{\"tag\":\"Design\",\"score\":0.133492187},{\"tag\":\"Toy\",\"score\":0.089353576},{\"tag\":\"Lunch\",\"score\":0.068848282},{\"tag\":\"Person\",\"score\":0.068477534},{\"tag\":\"Clothing\",\"score\":0.064856313}]}"}
[2019-12-21 15:58:24,951]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    return data['output']
TypeError: string indices must be integers
[2019-12-21 15:58:24,954]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:59:03,760]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    return data["output"]
TypeError: string indices must be integers
[2019-12-21 15:59:03,764]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:59:51,378]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{"}
[2019-12-21 16:00:16,670]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    return data[0]['output']
TypeError: string indices must be integers
[2019-12-21 16:00:16,673]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:00:32,129]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"output\":[{\"tag\":\"Art\",\"score\":0.40754357},{\"tag\":\"Food\",\"score\":0.27293992},{\"tag\":\"Play\",\"score\":0.241263077},{\"tag\":\"Meal\",\"score\":0.207908183},{\"tag\":\"Yellow\",\"score\":0.177275434},{\"tag\":\"Design\",\"score\":0.133492187},{\"tag\":\"Toy\",\"score\":0.089353576},{\"tag\":\"Lunch\",\"score\":0.068848282},{\"tag\":\"Person\",\"score\":0.068477534},{\"tag\":\"Clothing\",\"score\":0.064856313}]}"}
[2019-12-21 16:01:58,753]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"code\":400,\"message\":\"No image file\"}"}
[2019-12-21 16:02:33,375]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"output\":[{\"tag\":\"Art\",\"score\":0.40754357},{\"tag\":\"Food\",\"score\":0.27293992},{\"tag\":\"Play\",\"score\":0.241263077},{\"tag\":\"Meal\",\"score\":0.207908183},{\"tag\":\"Yellow\",\"score\":0.177275434},{\"tag\":\"Design\",\"score\":0.133492187},{\"tag\":\"Toy\",\"score\":0.089353576},{\"tag\":\"Lunch\",\"score\":0.068848282},{\"tag\":\"Person\",\"score\":0.068477534},{\"tag\":\"Clothing\",\"score\":0.064856313}]}"}
[2019-12-21 16:03:02,580]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 18, in post
    args = parser.parse_args()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/reqparse.py", line 325, in parse_args
    value, found = arg.parse(req, self.bundle_errors)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/reqparse.py", line 191, in parse
    if name in source:
TypeError: a bytes-like object is required, not 'str'
[2019-12-21 16:03:02,583]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:03:44,567]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 18, in post
    args = parser.parse_args()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/reqparse.py", line 325, in parse_args
    value, found = arg.parse(req, self.bundle_errors)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/reqparse.py", line 191, in parse
    if name in source:
TypeError: a bytes-like object is required, not 'str'
[2019-12-21 16:03:44,568]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:03:54,627]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"output\":[{\"tag\":\"Art\",\"score\":0.40754357},{\"tag\":\"Food\",\"score\":0.27293992},{\"tag\":\"Play\",\"score\":0.241263077},{\"tag\":\"Meal\",\"score\":0.207908183},{\"tag\":\"Yellow\",\"score\":0.177275434},{\"tag\":\"Design\",\"score\":0.133492187},{\"tag\":\"Toy\",\"score\":0.089353576},{\"tag\":\"Lunch\",\"score\":0.068848282},{\"tag\":\"Person\",\"score\":0.068477534},{\"tag\":\"Clothing\",\"score\":0.064856313}]}"}
[2019-12-21 16:31:56,171]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 22, in post
    datajson = data.json()
AttributeError: 'str' object has no attribute 'json'
[2019-12-21 16:31:56,175]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:32:40,767]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"output\":[{\"tag\":\"Art\",\"score\":0.40754357},{\"tag\":\"Food\",\"score\":0.27293992},{\"tag\":\"Play\",\"score\":0.241263077},{\"tag\":\"Meal\",\"score\":0.207908183},{\"tag\":\"Yellow\",\"score\":0.177275434},{\"tag\":\"Design\",\"score\":0.133492187},{\"tag\":\"Toy\",\"score\":0.089353576},{\"tag\":\"Lunch\",\"score\":0.068848282},{\"tag\":\"Person\",\"score\":0.068477534},{\"tag\":\"Clothing\",\"score\":0.064856313}]}"}
[2019-12-21 16:33:58,153]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 22, in post
    datajson = data.json()
AttributeError: 'str' object has no attribute 'json'
[2019-12-21 16:33:58,155]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:34:28,447]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "{\"output\":[{\"tag\":\"Art\",\"score\":0.40754357},{\"tag\":\"Food\",\"score\":0.27293992},{\"tag\":\"Play\",\"score\":0.241263077},{\"tag\":\"Meal\",\"score\":0.207908183},{\"tag\":\"Yellow\",\"score\":0.177275434},{\"tag\":\"Design\",\"score\":0.133492187},{\"tag\":\"Toy\",\"score\":0.089353576},{\"tag\":\"Lunch\",\"score\":0.068848282},{\"tag\":\"Person\",\"score\":0.068477534},{\"tag\":\"Clothing\",\"score\":0.064856313}]}"}
[2019-12-21 16:51:08,939]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 462, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 491, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Response' is not JSON serializable
[2019-12-21 16:51:08,944]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:51:39,588]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": {"output": [{"tag": "Art", "score": 0.40754357}, {"tag": "Food", "score": 0.27293992}, {"tag": "Play", "score": 0.241263077}, {"tag": "Meal", "score": 0.207908183}, {"tag": "Yellow", "score": 0.177275434}, {"tag": "Design", "score": 0.133492187}, {"tag": "Toy", "score": 0.089353576}, {"tag": "Lunch", "score": 0.068848282}, {"tag": "Person", "score": 0.068477534}, {"tag": "Clothing", "score": 0.064856313}]}}
[2019-12-21 16:54:40,584]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": [{"tag": "Art", "score": 0.40754357}, {"tag": "Food", "score": 0.27293992}, {"tag": "Play", "score": 0.241263077}, {"tag": "Meal", "score": 0.207908183}, {"tag": "Yellow", "score": 0.177275434}, {"tag": "Design", "score": 0.133492187}, {"tag": "Toy", "score": 0.089353576}, {"tag": "Lunch", "score": 0.068848282}, {"tag": "Person", "score": 0.068477534}, {"tag": "Clothing", "score": 0.064856313}]}
[2019-12-21 16:55:13,786]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": {"tag": "Food", "score": 0.27293992}}
[2019-12-21 16:57:30,493]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    datajson = datajson['output']
KeyError: 'output'
[2019-12-21 16:57:30,497]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:58:09,101]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    datajson = datajson['output']
KeyError: 'output'
[2019-12-21 16:58:09,104]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:58:33,164]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 23, in post
    datajson = datajson['output']
KeyError: 'output'
[2019-12-21 16:58:33,167]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:58:48,629]{/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /imgrecognizer [POST]
Traceback (most recent call last):
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta6/Alta Fadzri's file/coba_RESTful/flaskenv/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta6/RESTApi-group-project/blueprints/paralleldot/resources.py", line 25, in post
    if data['tag'] == 'Food':
TypeError: string indices must be integers
[2019-12-21 16:58:48,634]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "POST", "code": "500 INTERNAL SERVER ERROR", "uri": "/imgrecognizer?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:59:20,064]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": {"Error": "Backend error. Please email at support@paralleldots.com to get this error resolved on priority.", "code": 500}}
[2019-12-21 16:59:54,517]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": [{"tag": "Art", "score": 0.40754357}, {"tag": "Food", "score": 0.27293992}, {"tag": "Play", "score": 0.241263077}, {"tag": "Meal", "score": 0.207908183}, {"tag": "Yellow", "score": 0.177275434}, {"tag": "Design", "score": 0.133492187}, {"tag": "Toy", "score": 0.089353576}, {"tag": "Lunch", "score": 0.068848282}, {"tag": "Person", "score": 0.068477534}, {"tag": "Clothing", "score": 0.064856313}]}
[2019-12-21 17:00:52,128]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": [{"tag": "Font", "score": 0.586098552}, {"tag": "Brand", "score": 0.520645797}, {"tag": "Gadget", "score": 0.498920858}, {"tag": "Mobile phone", "score": 0.311809063}, {"tag": "Multimedia", "score": 0.290152133}, {"tag": "Electronic device", "score": 0.196102872}, {"tag": "Electronics", "score": 0.169781581}, {"tag": "Smartphone", "score": 0.153473243}, {"tag": "Design", "score": 0.116039313}, {"tag": "Text", "score": 0.114505403}]}
[2019-12-21 17:01:46,796]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "SORRY, NO FOOD DETECTED!!!!"}
