[2019-12-21 14:48:15,662]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=fc072ffe40c35123812215871383404e&oe=5EA9E951", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 14:50:55,686]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=fc072ffe40c35123812215871383404e&oe=5EA9E951", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 15:20:17,899]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=fc072ffe40c35123812215871383404e&oe=5EA9E951", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 15:20:37,994]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=fc072ffe40c35123812215871383404e&oe=5EA9E951", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 15:21:55,308]{/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /instagram [GET]
Traceback (most recent call last):
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(110, 'Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/instagram/resources.py", line 12, in get
    def get(self):
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(110, 'Connection timed out'))
[2019-12-21 15:21:55,326]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/instagram?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:24:45,307]{/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /instagram [GET]
Traceback (most recent call last):
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/instagram/resources.py", line 14, in get
    rq = requests.get(self.url)
AttributeError: 'GetFotoandCaption' object has no attribute 'url'
[2019-12-21 15:24:45,309]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/instagram?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:25:39,701]{/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /instagram [GET]
Traceback (most recent call last):
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/instagram/resources.py", line 14, in get
    rq = requests.get(self.url)
AttributeError: 'GetFotoandCaption' object has no attribute 'url'
[2019-12-21 15:25:39,704]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/instagram?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:28:44,775]{/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /instagram [GET]
Traceback (most recent call last):
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/instagram/resources.py", line 14, in get
    rq = requests.get(self.url)
AttributeError: 'GetFotoandCaption' object has no attribute 'url'
[2019-12-21 15:28:44,776]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/instagram?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 15:28:54,459]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=fc072ffe40c35123812215871383404e&oe=5EA9E951", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 15:29:23,827]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/68842936_1001258380230151_6138644861286416599_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=_S-ERHBzCSYAX_NOYXZ&oh=a55ca65a5b8033c57e46dced3efe5e30&oe=5E98C075", "caption": "You cannot see the light without the darkness.\nThe beauty of light dwells in the heart of darkness.\nEven stars cannot shine without the darkness, right?\nWe all are lost stars just tryin to light up the dark.\n\nDear my light,\nThank you for being my light in my darkest times.\n\n#lightpainting #lightpaintingindonesia #lightpaintingphotography #lightpaintingworld #lightpaintingart"}}
[2019-12-21 15:40:47,755]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/13561763_1786101431669375_1462932704_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=qmWdQvGYYe8AX8ZwDmK&oh=c4a750f6218a3ea6dd704a9ea6c008cb&oe=5EB03439", "caption": "We are Ronin"}}
[2019-12-21 16:13:35,798]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 405, "method": "POST", "code": "405 METHOD NOT ALLOWED", "uri": "/faceplus?", "request": {}, "response": {"message": "The method is not allowed for the requested URL."}}
[2019-12-21 16:13:47,531]{/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /faceplus [GET]
Traceback (most recent call last):
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/faceplus/resources.py", line 23, in get
    confidence = content['confidence']
KeyError: 'confidence'
[2019-12-21 16:13:47,534]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/faceplus?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:19:25,101]{/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /faceplus [GET]
Traceback (most recent call last):
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/faceplus/resources.py", line 23, in get
    confidence = content["confidence"]
KeyError: 'confidence'
[2019-12-21 16:19:25,104]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/faceplus?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:20:41,497]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/faceplus?", "request": {}, "response": {"time_used": 104, "error_message": "INVALID_IMAGE_URL: image_url2", "request_id": "1576920041,c1593ec0-f55c-4f41-b4db-17487587cb7e"}}
[2019-12-21 16:22:41,471]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=fc072ffe40c35123812215871383404e&oe=5EA9E951", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 16:24:28,657]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=fc072ffe40c35123812215871383404e&oe=5EA9E951", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 16:24:52,657]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/e35/s150x150/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=98969fdb53d6c644e4da9185b5b63428&oe=5E773FD4", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 16:25:08,547]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/faceplus?", "request": {}, "response": {"time_used": 107, "error_message": "INVALID_IMAGE_URL: image_url2", "request_id": "1576920308,900ff81a-1430-4365-96e2-ac7c01671c20"}}
[2019-12-21 16:25:31,056]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/e35/s150x150/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=98969fdb53d6c644e4da9185b5b63428&oe=5E773FD4", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 16:26:14,952]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/faceplus?", "request": {}, "response": {"time_used": 105, "error_message": "INVALID_IMAGE_URL: image_url2", "request_id": "1576920374,f3b22352-8ac1-4189-b623-f9defc0c1c96"}}
[2019-12-21 16:27:25,330]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/faceplus?", "request": {}, "response": {"time_used": 81, "error_message": "INVALID_IMAGE_URL: image_url2", "request_id": "1576920445,223c0e93-5eb5-4d36-bce7-dbc64b1f7ff5"}}
[2019-12-21 16:27:40,317]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/faceplus?", "request": {}, "response": {"faces1": [{"face_rectangle": {"width": 129, "top": 99, "left": 284, "height": 129}, "face_token": "a85f8533f6b4db479d500cb3375c3f83"}], "faces2": [{"face_rectangle": {"width": 89, "top": 59, "left": 226, "height": 89}, "face_token": "2b9810832fdb80538960f551820d8b15"}], "time_used": 432, "thresholds": {"1e-3": 62.327, "1e-5": 73.975, "1e-4": 69.101}, "confidence": 21.28, "image_id2": "xyycoi89wcCUiNMEq70SZQ==", "image_id1": "1k8Drns1t6wtKGAEpOtYqg==", "request_id": "1576920459,b75bf6da-1d02-42af-9874-83e3bd032ce2"}}
[2019-12-21 16:28:32,209]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/faceplus?", "request": {}, "response": {"confidence": 21.278}}
[2019-12-21 16:29:00,295]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/faceplus?", "request": {}, "response": {"confidence": 21.278}}
[2019-12-21 16:29:12,257]{/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /faceplus [GET]
Traceback (most recent call last):
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/faceplus/resources.py", line 24, in get
    confidence = content["confidence"]
KeyError: 'confidence'
[2019-12-21 16:29:12,260]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/faceplus?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 16:30:22,921]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/e35/s150x150/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=98969fdb53d6c644e4da9185b5b63428&oe=5E773FD4", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 16:58:08,600]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/e35/s150x150/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=98969fdb53d6c644e4da9185b5b63428&oe=5E773FD4", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 16:58:26,164]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=fc072ffe40c35123812215871383404e&oe=5EA9E951", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 16:59:35,259]{/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py:1891} ERROR - Exception on /faceplus [GET]
Traceback (most recent call last):
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/env_flask/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/faceplus/resources.py", line 25, in get
    confidence = content["confidence"]
KeyError: 'confidence'
[2019-12-21 16:59:35,263]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:93} ERROR - REQUEST_LOG	{"status_code": 500, "method": "GET", "code": "500 INTERNAL SERVER ERROR", "uri": "/faceplus?", "request": {}, "response": {"message": "Internal Server Error"}}
[2019-12-21 17:00:16,769]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/faceplus?", "request": {}, "response": {"confidence": 21.28}}
[2019-12-21 17:05:25,294]{/home/alta4/Alterra Batch 4/Flask/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "GET", "code": "200 OK", "uri": "/instagram?", "request": {}, "response": {"foto": "https://scontent.cdninstagram.com/v/t51.2885-15/sh0.08/e35/s640x640/66391286_2294013900705901_4376247166940848407_n.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=lgXLtbNOIWcAX9jezE1&oh=fc072ffe40c35123812215871383404e&oe=5EA9E951", "caption": "Semoga gelar ini berkah dunia akhirat. Aamiin"}}
[2019-12-21 17:36:31,364]{/home/alta6/RESTApi-group-project/blueprints/__init__.py:71} INFO - REQUEST_LOG	{"status_code": 200, "method": "POST", "code": "200 OK", "uri": "/imgrecognizer?", "request": {}, "response": "SORRY, NO FOOD DETECTED!!!!"}
